# Generated by Django 3.1.1 on 2020-09-24 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mq_json', '0002_auto_20200924_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='messages',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('recipient_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_uuid_fk', to='mq_json.client')),
                ('sender_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_uuid_fk', to='mq_json.client')),
            ],
        ),
    ]
